---@class onehalf
---@field config onehalfConfig
---@field palette onehalfPalette
local onehalf = {}

---@alias Contrast "hard" | "soft" | ""

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class onehalfConfig
---@field bold boolean?
---@field contrast Contrast?
---@field dim_inactive boolean?
---@field inverse boolean?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field italic ItalicConfig?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
---@field strikethrough boolean?
---@field terminal_colors boolean?
---@field transparent_mode boolean?
---@field undercurl boolean?
---@field underline boolean?
local default_config = {
    terminal_colors = true,
    undercurl = true,
    underline = true,
    bold = true,
    italic = {
        strings = true,
        emphasis = true,
        comments = true,
        operators = false,
        folds = true,
    },
    strikethrough = true,
    invert_selection = false,
    invert_signs = false,
    invert_tabline = false,
    inverse = true,
    contrast = "",
    palette_overrides = {},
    overrides = {},
    dim_inactive = false,
    transparent_mode = false,
}

onehalf.config = vim.deepcopy(default_config)

-- main onehalf color palette
---@class onehalfPalette
onehalf.palette = {
    dark0_hard = "#21252b", -- Deep background
    dark0 = "#282c34",      -- Main background
    dark0_soft = "#2c313a", -- Lighter background
    dark1 = "#313640",      -- Selection/Highlight
    dark2 = "#353b45",
    dark3 = "#3e4451",
    dark4 = "#4b5263",  -- Comments / Grey
    light0_hard = "#ffffff",
    light0 = "#dcdfe4", -- Main foreground
    light0_soft = "#c8ccd4",
    light1 = "#abb2bf",
    light2 = "#9ea5b3",
    light3 = "#828997",
    light4 = "#5c6370",
    bright_red = "#e06c75",
    bright_green = "#98c379",
    bright_yellow = "#e5c07b",
    bright_blue = "#61afef",
    bright_purple = "#c678dd",
    bright_aqua = "#56b6c2",
    bright_orange = "#d19a66",
    neutral_red = "#e06c75",
    neutral_green = "#98c379",
    neutral_yellow = "#e5c07b",
    neutral_blue = "#61afef",
    neutral_purple = "#c678dd",
    neutral_aqua = "#56b6c2",
    neutral_orange = "#d19a66",
    faded_red = "#be5046",
    faded_green = "#73925d",
    faded_yellow = "#c1a269",
    faded_blue = "#4882b4",
    faded_purple = "#a361b7",
    faded_aqua = "#44919a",
    faded_orange = "#b28256",
    dark_red_hard = "#4b2c32",
    dark_red = "#3e272b",
    dark_green_hard = "#2c3230",
    dark_green = "#232726",
    gray = "#5c6370",
}

-- get a hex list of onehalf colors based on current bg and constrast config
local function get_colors()
    local p = onehalf.palette
    local config = onehalf.config

    for color, hex in pairs(config.palette_overrides) do
        p[color] = hex
    end

    local bg = vim.o.background
    local contrast = config.contrast

    local color_groups = {
        dark = {
            bg0 = p.dark0,
            bg1 = p.dark1,
            bg2 = p.dark2,
            bg3 = p.dark3,
            bg4 = p.dark4,
            fg0 = p.light0,
            fg1 = p.light1,
            fg2 = p.light2,
            fg3 = p.light3,
            fg4 = p.light4,
            red = p.bright_red,
            green = p.bright_green,
            yellow = p.bright_yellow,
            blue = p.bright_blue,
            purple = p.bright_purple,
            aqua = p.bright_aqua,
            orange = p.bright_orange,
            neutral_red = p.neutral_red,
            neutral_green = p.neutral_green,
            neutral_yellow = p.neutral_yellow,
            neutral_blue = p.neutral_blue,
            neutral_purple = p.neutral_purple,
            neutral_aqua = p.neutral_aqua,
            dark_red = p.dark_red,
            dark_green = p.dark_green,
            dark_aqua = p.dark_aqua,
            gray = p.gray,
        },
        light = {
            bg0 = p.light0,
            bg1 = p.light1,
            bg2 = p.light2,
            bg3 = p.light3,
            bg4 = p.light4,
            fg0 = p.dark0,
            fg1 = p.dark1,
            fg2 = p.dark2,
            fg3 = p.dark3,
            fg4 = p.dark4,
            red = p.faded_red,
            green = p.faded_green,
            yellow = p.faded_yellow,
            blue = p.faded_blue,
            purple = p.faded_purple,
            aqua = p.faded_aqua,
            orange = p.faded_orange,
            neutral_red = p.neutral_red,
            neutral_green = p.neutral_green,
            neutral_yellow = p.neutral_yellow,
            neutral_blue = p.neutral_blue,
            neutral_purple = p.neutral_purple,
            neutral_aqua = p.neutral_aqua,
            dark_red = p.light_red,
            dark_green = p.light_green,
            dark_aqua = p.light_aqua,
            gray = p.gray,
        },
    }

    if contrast ~= nil and contrast ~= "" then
        color_groups[bg].bg0 = p[bg .. "0_" .. contrast]
        color_groups[bg].dark_red = p[bg .. "_red_" .. contrast]
        color_groups[bg].dark_green = p[bg .. "_green_" .. contrast]
        color_groups[bg].dark_aqua = p[bg .. "_aqua_" .. contrast]
    end

    return color_groups[bg]
end

local function get_groups()
    local colors = get_colors()
    local config = onehalf.config

    if config.terminal_colors then
        local term_colors = {
            colors.bg0,
            colors.neutral_red,
            colors.neutral_green,
            colors.neutral_yellow,
            colors.neutral_blue,
            colors.neutral_purple,
            colors.neutral_aqua,
            colors.fg4,
            colors.gray,
            colors.red,
            colors.green,
            colors.yellow,
            colors.blue,
            colors.purple,
            colors.aqua,
            colors.fg1,
        }
        for index, value in ipairs(term_colors) do
            vim.g["terminal_color_" .. index - 1] = value
        end
    end

    local groups = {
        onehalfFg0 = { fg = colors.fg0 },
        onehalfFg1 = { fg = colors.fg1 },
        onehalfFg2 = { fg = colors.fg2 },
        onehalfFg3 = { fg = colors.fg3 },
        onehalfFg4 = { fg = colors.fg4 },
        onehalfGray = { fg = colors.gray },
        onehalfBg0 = { fg = colors.bg0 },
        onehalfBg1 = { fg = colors.bg1 },
        onehalfBg2 = { fg = colors.bg2 },
        onehalfBg3 = { fg = colors.bg3 },
        onehalfBg4 = { fg = colors.bg4 },
        onehalfRed = { fg = colors.red },
        onehalfRedBold = { fg = colors.red, bold = config.bold },
        onehalfGreen = { fg = colors.green },
        onehalfGreenBold = { fg = colors.green, bold = config.bold },
        onehalfYellow = { fg = colors.yellow },
        onehalfYellowBold = { fg = colors.yellow, bold = config.bold },
        onehalfBlue = { fg = colors.blue },
        onehalfBlueBold = { fg = colors.blue, bold = config.bold },
        onehalfPurple = { fg = colors.purple },
        onehalfPurpleBold = { fg = colors.purple, bold = config.bold },
        onehalfAqua = { fg = colors.aqua },
        onehalfAquaBold = { fg = colors.aqua, bold = config.bold },
        onehalfOrange = { fg = colors.orange },
        onehalfOrangeBold = { fg = colors.orange, bold = config.bold },
        onehalfRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
            or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
        onehalfGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
            or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
        onehalfYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
            or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
        onehalfBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
            or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
        onehalfPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
            or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
        onehalfAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
            or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
        onehalfOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
            or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
        onehalfRedUnderline = { undercurl = config.undercurl, sp = colors.red },
        onehalfGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
        onehalfYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
        onehalfBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
        onehalfPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
        onehalfAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
        onehalfOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
        Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
        NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
        NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
        CursorLine = { bg = colors.bg1 },
        CursorColumn = { link = "CursorLine" },
        TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
        TabLine = { link = "TabLineFill" },
        MatchParen = { bg = colors.bg3, bold = config.bold },
        ColorColumn = { bg = colors.bg1 },
        Conceal = { fg = colors.blue },
        CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
        NonText = { link = "onehalfBg2" },
        SpecialKey = { link = "onehalfFg4" },
        Visual = { bg = colors.bg3, reverse = config.invert_selection },
        VisualNOS = { link = "Visual" },
        Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
        IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
        CurSearch = { link = "IncSearch" },
        QuickFixLine = { link = "onehalfPurple" },
        Underlined = { fg = colors.blue, underline = config.underline },
        StatusLine = { fg = colors.fg1, bg = colors.bg2 },
        StatusLineNC = { fg = colors.fg4, bg = colors.bg1 },
        WinBar = { fg = colors.fg4, bg = colors.bg0 },
        WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
        WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
        WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
        Directory = { link = "onehalfGreenBold" },
        Title = { link = "onehalfGreenBold" },
        ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        MoreMsg = { link = "onehalfYellowBold" },
        ModeMsg = { link = "onehalfYellowBold" },
        Question = { link = "onehalfOrangeBold" },
        WarningMsg = { link = "onehalfRedBold" },
        LineNr = { fg = colors.bg4 },
        SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
        Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
        FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
        Cursor = { reverse = config.inverse },
        vCursor = { link = "Cursor" },
        iCursor = { link = "Cursor" },
        lCursor = { link = "Cursor" },
        Special = { link = "onehalfOrange" },
        Comment = { fg = colors.gray, italic = config.italic.comments },
        Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
        Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
        Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
        Statement = { link = "onehalfRed" },
        Conditional = { link = "onehalfRed" },
        Repeat = { link = "onehalfRed" },
        Label = { link = "onehalfRed" },
        Exception = { link = "onehalfRed" },
        Operator = { fg = colors.orange, italic = config.italic.operators },
        Keyword = { link = "onehalfRed" },
        Identifier = { link = "onehalfBlue" },
        Function = { link = "onehalfGreenBold" },
        PreProc = { link = "onehalfAqua" },
        Include = { link = "onehalfAqua" },
        Define = { link = "onehalfAqua" },
        Macro = { link = "onehalfAqua" },
        PreCondit = { link = "onehalfAqua" },
        Constant = { link = "onehalfPurple" },
        Character = { link = "onehalfPurple" },
        String = { fg = colors.green, italic = config.italic.strings },
        Boolean = { link = "onehalfPurple" },
        Number = { link = "onehalfPurple" },
        Float = { link = "onehalfPurple" },
        Type = { link = "onehalfYellow" },
        StorageClass = { link = "onehalfOrange" },
        Structure = { link = "onehalfAqua" },
        Typedef = { link = "onehalfYellow" },
        Pmenu = { fg = colors.fg1, bg = colors.bg2 },
        PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
        PmenuSbar = { bg = colors.bg2 },
        PmenuThumb = { bg = colors.bg4 },
        DiffDelete = { bg = colors.dark_red },
        DiffAdd = { bg = colors.dark_green },
        DiffChange = { bg = colors.dark_aqua },
        DiffText = { bg = colors.yellow, fg = colors.bg0 },
        SpellCap = { link = "onehalfBlueUnderline" },
        SpellBad = { link = "onehalfRedUnderline" },
        SpellLocal = { link = "onehalfAquaUnderline" },
        SpellRare = { link = "onehalfPurpleUnderline" },
        Whitespace = { fg = colors.bg2 },
        Delimiter = { link = "onehalfOrange" },
        EndOfBuffer = { link = "NonText" },
        DiagnosticError = { link = "onehalfRed" },
        DiagnosticWarn = { link = "onehalfYellow" },
        DiagnosticInfo = { link = "onehalfBlue" },
        DiagnosticDeprecated = { strikethrough = config.strikethrough },
        DiagnosticHint = { link = "onehalfAqua" },
        DiagnosticOk = { link = "onehalfGreen" },
        DiagnosticSignError = { link = "onehalfRedSign" },
        DiagnosticSignWarn = { link = "onehalfYellowSign" },
        DiagnosticSignInfo = { link = "onehalfBlueSign" },
        DiagnosticSignHint = { link = "onehalfAquaSign" },
        DiagnosticSignOk = { link = "onehalfGreenSign" },
        DiagnosticUnderlineError = { link = "onehalfRedUnderline" },
        DiagnosticUnderlineWarn = { link = "onehalfYellowUnderline" },
        DiagnosticUnderlineInfo = { link = "onehalfBlueUnderline" },
        DiagnosticUnderlineHint = { link = "onehalfAquaUnderline" },
        DiagnosticUnderlineOk = { link = "onehalfGreenUnderline" },
        DiagnosticFloatingError = { link = "onehalfRed" },
        DiagnosticFloatingWarn = { link = "onehalfOrange" },
        DiagnosticFloatingInfo = { link = "onehalfBlue" },
        DiagnosticFloatingHint = { link = "onehalfAqua" },
        DiagnosticFloatingOk = { link = "onehalfGreen" },
        DiagnosticVirtualTextError = { link = "onehalfRed" },
        DiagnosticVirtualTextWarn = { link = "onehalfYellow" },
        DiagnosticVirtualTextInfo = { link = "onehalfBlue" },
        DiagnosticVirtualTextHint = { link = "onehalfAqua" },
        DiagnosticVirtualTextOk = { link = "onehalfGreen" },
        LspReferenceRead = { link = "onehalfYellowBold" },
        LspReferenceTarget = { link = "Visual" },
        LspReferenceText = { link = "onehalfYellowBold" },
        LspReferenceWrite = { link = "onehalfOrangeBold" },
        LspCodeLens = { link = "onehalfGray" },
        LspSignatureActiveParameter = { link = "Search" },
        gitcommitSelectedFile = { link = "onehalfGreen" },
        gitcommitDiscardedFile = { link = "onehalfRed" },
        GitSignsAdd = { link = "onehalfGreen" },
        GitSignsChange = { link = "onehalfOrange" },
        GitSignsDelete = { link = "onehalfRed" },
        NvimTreeSymlink = { fg = colors.neutral_aqua },
        NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
        NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
        NvimTreeFileIcon = { fg = colors.light2 },
        NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
        NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
        NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
        NvimTreeImageFile = { fg = colors.neutral_purple },
        NvimTreeIndentMarker = { fg = colors.dark3 },
        NvimTreeGitDirty = { fg = colors.neutral_yellow },
        NvimTreeGitStaged = { fg = colors.neutral_yellow },
        NvimTreeGitMerge = { fg = colors.neutral_purple },
        NvimTreeGitRenamed = { fg = colors.neutral_purple },
        NvimTreeGitNew = { fg = colors.neutral_yellow },
        NvimTreeGitDeleted = { fg = colors.neutral_red },
        NvimTreeWindowPicker = { bg = colors.aqua },
        debugPC = { link = "DiffAdd" },
        debugBreakpoint = { link = "onehalfRedSign" },
        StartifyBracket = { link = "onehalfFg3" },
        StartifyFile = { link = "onehalfFg1" },
        StartifyNumber = { link = "onehalfBlue" },
        StartifyPath = { link = "onehalfGray" },
        StartifySlash = { link = "onehalfGray" },
        StartifySection = { link = "onehalfYellow" },
        StartifySpecial = { link = "onehalfBg2" },
        StartifyHeader = { link = "onehalfOrange" },
        StartifyFooter = { link = "onehalfBg2" },
        StartifyVar = { link = "StartifyPath" },
        StartifySelect = { link = "Title" },
        DirvishPathTail = { link = "onehalfAqua" },
        DirvishArg = { link = "onehalfYellow" },
        netrwDir = { link = "onehalfAqua" },
        netrwClassify = { link = "onehalfAqua" },
        netrwLink = { link = "onehalfGray" },
        netrwSymLink = { link = "onehalfFg1" },
        netrwExe = { link = "onehalfYellow" },
        netrwComment = { link = "onehalfGray" },
        netrwList = { link = "onehalfBlue" },
        netrwHelpCmd = { link = "onehalfAqua" },
        netrwCmdSep = { link = "onehalfFg3" },
        netrwVersion = { link = "onehalfGreen" },
        NERDTreeDir = { link = "onehalfAqua" },
        NERDTreeDirSlash = { link = "onehalfAqua" },
        NERDTreeOpenable = { link = "onehalfOrange" },
        NERDTreeClosable = { link = "onehalfOrange" },
        NERDTreeFile = { link = "onehalfFg1" },
        NERDTreeExecFile = { link = "onehalfYellow" },
        NERDTreeUp = { link = "onehalfGray" },
        NERDTreeCWD = { link = "onehalfGreen" },
        NERDTreeHelp = { link = "onehalfFg1" },
        NERDTreeToggleOn = { link = "onehalfGreen" },
        NERDTreeToggleOff = { link = "onehalfRed" },
        CocErrorSign = { link = "onehalfRedSign" },
        CocWarningSign = { link = "onehalfOrangeSign" },
        CocInfoSign = { link = "onehalfBlueSign" },
        CocHintSign = { link = "onehalfAquaSign" },
        CocErrorFloat = { link = "onehalfRed" },
        CocWarningFloat = { link = "onehalfOrange" },
        CocInfoFloat = { link = "onehalfBlue" },
        CocHintFloat = { link = "onehalfAqua" },
        CocDiagnosticsError = { link = "onehalfRed" },
        CocDiagnosticsWarning = { link = "onehalfOrange" },
        CocDiagnosticsInfo = { link = "onehalfBlue" },
        CocDiagnosticsHint = { link = "onehalfAqua" },
        CocSearch = { link = "onehalfBlue" },
        CocSelectedText = { link = "onehalfRed" },
        CocMenuSel = { link = "PmenuSel" },
        CocCodeLens = { link = "onehalfGray" },
        CocErrorHighlight = { link = "onehalfRedUnderline" },
        CocWarningHighlight = { link = "onehalfOrangeUnderline" },
        CocInfoHighlight = { link = "onehalfBlueUnderline" },
        CocHintHighlight = { link = "onehalfAquaUnderline" },
        SnacksPicker = { link = "onehalfFg1" },
        SnacksPickerBorder = { link = "SnacksPicker" },
        SnacksPickerListCursorLine = { link = "CursorLine" },
        SnacksPickerMatch = { link = "onehalfOrange" },
        SnacksPickerPrompt = { link = "onehalfRed" },
        SnacksPickerTitle = { link = "SnacksPicker" },
        SnacksPickerDir = { link = "onehalfGray" },
        SnacksPickerPathHidden = { link = "onehalfGray" },
        SnacksPickerGitStatusUntracked = { link = "onehalfGray" },
        SnacksPickerPathIgnored = { link = "onehalfBg3" },
        TelescopeNormal = { link = "onehalfFg1" },
        TelescopeSelection = { link = "CursorLine" },
        TelescopeSelectionCaret = { link = "onehalfRed" },
        TelescopeMultiSelection = { link = "onehalfGray" },
        TelescopeBorder = { link = "TelescopeNormal" },
        TelescopePromptBorder = { link = "TelescopeNormal" },
        TelescopeResultsBorder = { link = "TelescopeNormal" },
        TelescopePreviewBorder = { link = "TelescopeNormal" },
        TelescopeMatching = { link = "onehalfOrange" },
        TelescopePromptPrefix = { link = "onehalfRed" },
        TelescopePrompt = { link = "TelescopeNormal" },
        CmpItemAbbr = { link = "onehalfFg0" },
        CmpItemAbbrDeprecated = { link = "onehalfFg1" },
        CmpItemAbbrMatch = { link = "onehalfBlueBold" },
        CmpItemAbbrMatchFuzzy = { link = "onehalfBlueUnderline" },
        CmpItemMenu = { link = "onehalfGray" },
        CmpItemKindText = { link = "onehalfOrange" },
        CmpItemKindVariable = { link = "onehalfOrange" },
        CmpItemKindMethod = { link = "onehalfBlue" },
        CmpItemKindFunction = { link = "onehalfBlue" },
        CmpItemKindConstructor = { link = "onehalfYellow" },
        CmpItemKindUnit = { link = "onehalfBlue" },
        CmpItemKindField = { link = "onehalfBlue" },
        CmpItemKindClass = { link = "onehalfYellow" },
        CmpItemKindInterface = { link = "onehalfYellow" },
        CmpItemKindModule = { link = "onehalfBlue" },
        CmpItemKindProperty = { link = "onehalfBlue" },
        CmpItemKindValue = { link = "onehalfOrange" },
        CmpItemKindEnum = { link = "onehalfYellow" },
        CmpItemKindOperator = { link = "onehalfYellow" },
        CmpItemKindKeyword = { link = "onehalfPurple" },
        CmpItemKindEvent = { link = "onehalfPurple" },
        CmpItemKindReference = { link = "onehalfPurple" },
        CmpItemKindColor = { link = "onehalfPurple" },
        CmpItemKindSnippet = { link = "onehalfGreen" },
        CmpItemKindFile = { link = "onehalfBlue" },
        CmpItemKindFolder = { link = "onehalfBlue" },
        CmpItemKindEnumMember = { link = "onehalfAqua" },
        CmpItemKindConstant = { link = "onehalfOrange" },
        CmpItemKindStruct = { link = "onehalfYellow" },
        CmpItemKindTypeParameter = { link = "onehalfYellow" },
        CmpItemKindTextIcon = { link = "CmpItemKindText" },
        CmpItemKindVariableIcon = { link = "CmpItemKindVariable" },
        CmpItemKindMethodIcon = { link = "CmpItemKindMethod" },
        CmpItemKindFunctionIcon = { link = "CmpItemKindFunction" },
        CmpItemKindConstructorIcon = { link = "CmpItemKindConstructor" },
        CmpItemKindUnitIcon = { link = "CmpItemKindUnit" },
        CmpItemKindFieldIcon = { link = "CmpItemKindField" },
        CmpItemKindClassIcon = { link = "CmpItemKindClass" },
        CmpItemKindInterfaceIcon = { link = "CmpItemKindInterface" },
        CmpItemKindModuleIcon = { link = "CmpItemKindModule" },
        CmpItemKindPropertyIcon = { link = "CmpItemKindProperty" },
        CmpItemKindValueIcon = { link = "CmpItemKindValue" },
        CmpItemKindEnumIcon = { link = "CmpItemKindEnum" },
        CmpItemKindOperatorIcon = { link = "CmpItemKindOperator" },
        CmpItemKindKeywordIcon = { link = "CmpItemKindKeyword" },
        CmpItemKindEventIcon = { link = "CmpItemKindEvent" },
        CmpItemKindReferenceIcon = { link = "CmpItemKindReference" },
        CmpItemKindColorIcon = { link = "CmpItemKindColor" },
        CmpItemKindSnippetIcon = { link = "CmpItemKindSnippet" },
        CmpItemKindFileIcon = { link = "CmpItemKindFile" },
        CmpItemKindFolderIcon = { link = "CmpItemKindFolder" },
        CmpItemKindEnumMemberIcon = { link = "CmpItemKindEnumMember" },
        CmpItemKindConstantIcon = { link = "CmpItemKindConstant" },
        CmpItemKindStructIcon = { link = "CmpItemKindStruct" },
        CmpItemKindTypeParameterIcon = { link = "CmpItemKindTypeParameter" },
        BlinkCmpLabel = { link = "onehalfFg0" },
        BlinkCmpLabelDeprecated = { link = "onehalfFg1" },
        BlinkCmpLabelMatch = { link = "onehalfBlueBold" },
        BlinkCmpLabelDetail = { link = "onehalfGray" },
        BlinkCmpLabelDescription = { link = "onehalfGray" },
        BlinkCmpKindText = { link = "onehalfOrange" },
        BlinkCmpKindVariable = { link = "onehalfOrange" },
        BlinkCmpKindMethod = { link = "onehalfBlue" },
        BlinkCmpKindFunction = { link = "onehalfBlue" },
        BlinkCmpKindConstructor = { link = "onehalfYellow" },
        BlinkCmpKindUnit = { link = "onehalfBlue" },
        BlinkCmpKindField = { link = "onehalfBlue" },
        BlinkCmpKindClass = { link = "onehalfYellow" },
        BlinkCmpKindInterface = { link = "onehalfYellow" },
        BlinkCmpKindModule = { link = "onehalfBlue" },
        BlinkCmpKindProperty = { link = "onehalfBlue" },
        BlinkCmpKindValue = { link = "onehalfOrange" },
        BlinkCmpKindEnum = { link = "onehalfYellow" },
        BlinkCmpKindOperator = { link = "onehalfYellow" },
        BlinkCmpKindKeyword = { link = "onehalfPurple" },
        BlinkCmpKindEvent = { link = "onehalfPurple" },
        BlinkCmpKindReference = { link = "onehalfPurple" },
        BlinkCmpKindColor = { link = "onehalfPurple" },
        BlinkCmpKindSnippet = { link = "onehalfGreen" },
        BlinkCmpKindFile = { link = "onehalfBlue" },
        BlinkCmpKindFolder = { link = "onehalfBlue" },
        BlinkCmpKindEnumMember = { link = "onehalfAqua" },
        BlinkCmpKindConstant = { link = "onehalfOrange" },
        BlinkCmpKindStruct = { link = "onehalfYellow" },
        BlinkCmpKindTypeParameter = { link = "onehalfYellow" },
        BlinkCmpSource = { link = "onehalfGray" },
        BlinkCmpGhostText = { link = "onehalfBg4" },
        diffAdded = { link = "DiffAdd" },
        diffRemoved = { link = "DiffDelete" },
        diffChanged = { link = "DiffChange" },
        diffFile = { link = "onehalfOrange" },
        diffNewFile = { link = "onehalfYellow" },
        diffOldFile = { link = "onehalfOrange" },
        diffLine = { link = "onehalfBlue" },
        diffIndexLine = { link = "diffChanged" },
        NavicIconsFile = { link = "onehalfBlue" },
        NavicIconsModule = { link = "onehalfOrange" },
        NavicIconsNamespace = { link = "onehalfBlue" },
        NavicIconsPackage = { link = "onehalfAqua" },
        NavicIconsClass = { link = "onehalfYellow" },
        NavicIconsMethod = { link = "onehalfBlue" },
        NavicIconsProperty = { link = "onehalfAqua" },
        NavicIconsField = { link = "onehalfPurple" },
        NavicIconsConstructor = { link = "onehalfBlue" },
        NavicIconsEnum = { link = "onehalfPurple" },
        NavicIconsInterface = { link = "onehalfGreen" },
        NavicIconsFunction = { link = "onehalfBlue" },
        NavicIconsVariable = { link = "onehalfPurple" },
        NavicIconsConstant = { link = "onehalfOrange" },
        NavicIconsString = { link = "onehalfGreen" },
        NavicIconsNumber = { link = "onehalfOrange" },
        NavicIconsBoolean = { link = "onehalfOrange" },
        NavicIconsArray = { link = "onehalfOrange" },
        NavicIconsObject = { link = "onehalfOrange" },
        NavicIconsKey = { link = "onehalfAqua" },
        NavicIconsNull = { link = "onehalfOrange" },
        NavicIconsEnumMember = { link = "onehalfYellow" },
        NavicIconsStruct = { link = "onehalfPurple" },
        NavicIconsEvent = { link = "onehalfYellow" },
        NavicIconsOperator = { link = "onehalfRed" },
        NavicIconsTypeParameter = { link = "onehalfRed" },
        NavicText = { link = "onehalfWhite" },
        NavicSeparator = { link = "onehalfWhite" },
        htmlTag = { link = "onehalfAquaBold" },
        htmlEndTag = { link = "onehalfAquaBold" },
        htmlTagName = { link = "onehalfBlue" },
        htmlArg = { link = "onehalfOrange" },
        htmlTagN = { link = "onehalfFg1" },
        htmlSpecialTagName = { link = "onehalfBlue" },
        htmlLink = { fg = colors.fg4, underline = config.underline },
        htmlSpecialChar = { link = "onehalfRed" },
        htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
        htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
        htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
        htmlBoldUnderlineItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            bold = config.bold,
            italic = true,
            underline = config.underline,
        },
        htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
        htmlUnderlineItalic = {
            fg = colors.fg0,
            bg = colors.bg0,
            italic = true,
            underline = config.underline,
        },
        htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
        xmlTag = { link = "onehalfAquaBold" },
        xmlEndTag = { link = "onehalfAquaBold" },
        xmlTagName = { link = "onehalfBlue" },
        xmlEqual = { link = "onehalfBlue" },
        docbkKeyword = { link = "onehalfAquaBold" },
        xmlDocTypeDecl = { link = "onehalfGray" },
        xmlDocTypeKeyword = { link = "onehalfPurple" },
        xmlCdataStart = { link = "onehalfGray" },
        xmlCdataCdata = { link = "onehalfPurple" },
        dtdFunction = { link = "onehalfGray" },
        dtdTagName = { link = "onehalfPurple" },
        xmlAttrib = { link = "onehalfOrange" },
        xmlProcessingDelim = { link = "onehalfGray" },
        dtdParamEntityPunct = { link = "onehalfGray" },
        dtdParamEntityDPunct = { link = "onehalfGray" },
        xmlAttribPunct = { link = "onehalfGray" },
        xmlEntity = { link = "onehalfRed" },
        xmlEntityPunct = { link = "onehalfRed" },
        clojureKeyword = { link = "onehalfBlue" },
        clojureCond = { link = "onehalfOrange" },
        clojureSpecial = { link = "onehalfOrange" },
        clojureDefine = { link = "onehalfOrange" },
        clojureFunc = { link = "onehalfYellow" },
        clojureRepeat = { link = "onehalfYellow" },
        clojureCharacter = { link = "onehalfAqua" },
        clojureStringEscape = { link = "onehalfAqua" },
        clojureException = { link = "onehalfRed" },
        clojureRegexp = { link = "onehalfAqua" },
        clojureRegexpEscape = { link = "onehalfAqua" },
        clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
        clojureRegexpMod = { link = "clojureRegexpCharClass" },
        clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
        clojureParen = { link = "onehalfFg3" },
        clojureAnonArg = { link = "onehalfYellow" },
        clojureVariable = { link = "onehalfBlue" },
        clojureMacro = { link = "onehalfOrange" },
        clojureMeta = { link = "onehalfYellow" },
        clojureDeref = { link = "onehalfYellow" },
        clojureQuote = { link = "onehalfYellow" },
        clojureUnquote = { link = "onehalfYellow" },
        cOperator = { link = "onehalfPurple" },
        cppOperator = { link = "onehalfPurple" },
        cStructure = { link = "onehalfOrange" },
        pythonBuiltin = { link = "onehalfOrange" },
        pythonBuiltinObj = { link = "onehalfOrange" },
        pythonBuiltinFunc = { link = "onehalfOrange" },
        pythonFunction = { link = "onehalfAqua" },
        pythonDecorator = { link = "onehalfRed" },
        pythonInclude = { link = "onehalfBlue" },
        pythonImport = { link = "onehalfBlue" },
        pythonRun = { link = "onehalfBlue" },
        pythonCoding = { link = "onehalfBlue" },
        pythonOperator = { link = "onehalfRed" },
        pythonException = { link = "onehalfRed" },
        pythonExceptions = { link = "onehalfPurple" },
        pythonBoolean = { link = "onehalfPurple" },
        pythonDot = { link = "onehalfFg3" },
        pythonConditional = { link = "onehalfRed" },
        pythonRepeat = { link = "onehalfRed" },
        pythonDottedName = { link = "onehalfGreenBold" },
        cssBraces = { link = "onehalfBlue" },
        cssFunctionName = { link = "onehalfYellow" },
        cssIdentifier = { link = "onehalfOrange" },
        cssClassName = { link = "onehalfGreen" },
        cssColor = { link = "onehalfBlue" },
        cssSelectorOp = { link = "onehalfBlue" },
        cssSelectorOp2 = { link = "onehalfBlue" },
        cssImportant = { link = "onehalfGreen" },
        cssVendor = { link = "onehalfFg1" },
        cssTextProp = { link = "onehalfAqua" },
        cssAnimationProp = { link = "onehalfAqua" },
        cssUIProp = { link = "onehalfYellow" },
        cssTransformProp = { link = "onehalfAqua" },
        cssTransitionProp = { link = "onehalfAqua" },
        cssPrintProp = { link = "onehalfAqua" },
        cssPositioningProp = { link = "onehalfYellow" },
        cssBoxProp = { link = "onehalfAqua" },
        cssFontDescriptorProp = { link = "onehalfAqua" },
        cssFlexibleBoxProp = { link = "onehalfAqua" },
        cssBorderOutlineProp = { link = "onehalfAqua" },
        cssBackgroundProp = { link = "onehalfAqua" },
        cssMarginProp = { link = "onehalfAqua" },
        cssListProp = { link = "onehalfAqua" },
        cssTableProp = { link = "onehalfAqua" },
        cssFontProp = { link = "onehalfAqua" },
        cssPaddingProp = { link = "onehalfAqua" },
        cssDimensionProp = { link = "onehalfAqua" },
        cssRenderProp = { link = "onehalfAqua" },
        cssColorProp = { link = "onehalfAqua" },
        cssGeneratedContentProp = { link = "onehalfAqua" },
        javaScriptBraces = { link = "onehalfFg1" },
        javaScriptFunction = { link = "onehalfAqua" },
        javaScriptIdentifier = { link = "onehalfRed" },
        javaScriptMember = { link = "onehalfBlue" },
        javaScriptNumber = { link = "onehalfPurple" },
        javaScriptNull = { link = "onehalfPurple" },
        javaScriptParens = { link = "onehalfFg3" },
        typescriptReserved = { link = "onehalfAqua" },
        typescriptLabel = { link = "onehalfAqua" },
        typescriptFuncKeyword = { link = "onehalfAqua" },
        typescriptIdentifier = { link = "onehalfOrange" },
        typescriptBraces = { link = "onehalfFg1" },
        typescriptEndColons = { link = "onehalfFg1" },
        typescriptDOMObjects = { link = "onehalfFg1" },
        typescriptAjaxMethods = { link = "onehalfFg1" },
        typescriptLogicSymbols = { link = "onehalfFg1" },
        typescriptDocSeeTag = { link = "Comment" },
        typescriptDocParam = { link = "Comment" },
        typescriptDocTags = { link = "vimCommentTitle" },
        typescriptGlobalObjects = { link = "onehalfFg1" },
        typescriptParens = { link = "onehalfFg3" },
        typescriptOpSymbols = { link = "onehalfFg3" },
        typescriptHtmlElemProperties = { link = "onehalfFg1" },
        typescriptNull = { link = "onehalfPurple" },
        typescriptInterpolationDelimiter = { link = "onehalfAqua" },
        purescriptModuleKeyword = { link = "onehalfAqua" },
        purescriptModuleName = { link = "onehalfFg1" },
        purescriptWhere = { link = "onehalfAqua" },
        purescriptDelimiter = { link = "onehalfFg4" },
        purescriptType = { link = "onehalfFg1" },
        purescriptImportKeyword = { link = "onehalfAqua" },
        purescriptHidingKeyword = { link = "onehalfAqua" },
        purescriptAsKeyword = { link = "onehalfAqua" },
        purescriptStructure = { link = "onehalfAqua" },
        purescriptOperator = { link = "onehalfBlue" },
        purescriptTypeVar = { link = "onehalfFg1" },
        purescriptConstructor = { link = "onehalfFg1" },
        purescriptFunction = { link = "onehalfFg1" },
        purescriptConditional = { link = "onehalfOrange" },
        purescriptBacktick = { link = "onehalfOrange" },
        coffeeExtendedOp = { link = "onehalfFg3" },
        coffeeSpecialOp = { link = "onehalfFg3" },
        coffeeCurly = { link = "onehalfOrange" },
        coffeeParen = { link = "onehalfFg3" },
        coffeeBracket = { link = "onehalfOrange" },
        rubyStringDelimiter = { link = "onehalfGreen" },
        rubyInterpolationDelimiter = { link = "onehalfAqua" },
        rubyDefinedOperator = { link = "rubyKeyword" },
        objcTypeModifier = { link = "onehalfRed" },
        objcDirective = { link = "onehalfBlue" },
        goDirective = { link = "onehalfAqua" },
        goConstants = { link = "onehalfPurple" },
        goDeclaration = { link = "onehalfRed" },
        goDeclType = { link = "onehalfBlue" },
        goBuiltins = { link = "onehalfOrange" },
        luaIn = { link = "onehalfRed" },
        luaFunction = { link = "onehalfAqua" },
        luaTable = { link = "onehalfOrange" },
        moonSpecialOp = { link = "onehalfFg3" },
        moonExtendedOp = { link = "onehalfFg3" },
        moonFunction = { link = "onehalfFg3" },
        moonObject = { link = "onehalfYellow" },
        javaAnnotation = { link = "onehalfBlue" },
        javaDocTags = { link = "onehalfAqua" },
        javaCommentTitle = { link = "vimCommentTitle" },
        javaParen = { link = "onehalfFg3" },
        javaParen1 = { link = "onehalfFg3" },
        javaParen2 = { link = "onehalfFg3" },
        javaParen3 = { link = "onehalfFg3" },
        javaParen4 = { link = "onehalfFg3" },
        javaParen5 = { link = "onehalfFg3" },
        javaOperator = { link = "onehalfOrange" },
        javaVarArg = { link = "onehalfGreen" },
        elixirDocString = { link = "Comment" },
        elixirStringDelimiter = { link = "onehalfGreen" },
        elixirInterpolationDelimiter = { link = "onehalfAqua" },
        elixirModuleDeclaration = { link = "onehalfYellow" },
        scalaNameDefinition = { link = "onehalfFg1" },
        scalaCaseFollowing = { link = "onehalfFg1" },
        scalaCapitalWord = { link = "onehalfFg1" },
        scalaTypeExtension = { link = "onehalfFg1" },
        scalaKeyword = { link = "onehalfRed" },
        scalaKeywordModifier = { link = "onehalfRed" },
        scalaSpecial = { link = "onehalfAqua" },
        scalaOperator = { link = "onehalfFg1" },
        scalaTypeDeclaration = { link = "onehalfYellow" },
        scalaTypeTypePostDeclaration = { link = "onehalfYellow" },
        scalaInstanceDeclaration = { link = "onehalfFg1" },
        scalaInterpolation = { link = "onehalfAqua" },
        markdownItalic = { fg = colors.fg3, italic = true },
        markdownBold = { fg = colors.fg3, bold = config.bold },
        markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
        markdownH1 = { link = "onehalfGreenBold" },
        markdownH2 = { link = "onehalfGreenBold" },
        markdownH3 = { link = "onehalfYellowBold" },
        markdownH4 = { link = "onehalfYellowBold" },
        markdownH5 = { link = "onehalfYellow" },
        markdownH6 = { link = "onehalfYellow" },
        markdownCode = { link = "onehalfAqua" },
        markdownCodeBlock = { link = "onehalfAqua" },
        markdownCodeDelimiter = { link = "onehalfAqua" },
        markdownBlockquote = { link = "onehalfGray" },
        markdownListMarker = { link = "onehalfGray" },
        markdownOrderedListMarker = { link = "onehalfGray" },
        markdownRule = { link = "onehalfGray" },
        markdownHeadingRule = { link = "onehalfGray" },
        markdownUrlDelimiter = { link = "onehalfFg3" },
        markdownLinkDelimiter = { link = "onehalfFg3" },
        markdownLinkTextDelimiter = { link = "onehalfFg3" },
        markdownHeadingDelimiter = { link = "onehalfOrange" },
        markdownUrl = { link = "onehalfPurple" },
        markdownUrlTitleDelimiter = { link = "onehalfGreen" },
        markdownLinkText = { fg = colors.gray, underline = config.underline },
        markdownIdDeclaration = { link = "markdownLinkText" },
        haskellType = { link = "onehalfBlue" },
        haskellIdentifier = { link = "onehalfAqua" },
        haskellSeparator = { link = "onehalfFg4" },
        haskellDelimiter = { link = "onehalfOrange" },
        haskellOperators = { link = "onehalfPurple" },
        haskellBacktick = { link = "onehalfOrange" },
        haskellStatement = { link = "onehalfPurple" },
        haskellConditional = { link = "onehalfPurple" },
        haskellLet = { link = "onehalfRed" },
        haskellDefault = { link = "onehalfRed" },
        haskellWhere = { link = "onehalfRed" },
        haskellBottom = { link = "onehalfRedBold" },
        haskellImportKeywords = { link = "onehalfPurpleBold" },
        haskellDeclKeyword = { link = "onehalfOrange" },
        haskellDecl = { link = "onehalfOrange" },
        haskellDeriving = { link = "onehalfPurple" },
        haskellAssocType = { link = "onehalfAqua" },
        haskellNumber = { link = "onehalfAqua" },
        haskellPragma = { link = "onehalfRedBold" },
        haskellTH = { link = "onehalfAquaBold" },
        haskellForeignKeywords = { link = "onehalfGreen" },
        haskellKeyword = { link = "onehalfRed" },
        haskellFloat = { link = "onehalfAqua" },
        haskellInfix = { link = "onehalfPurple" },
        haskellQuote = { link = "onehalfGreenBold" },
        haskellShebang = { link = "onehalfYellowBold" },
        haskellLiquid = { link = "onehalfPurpleBold" },
        haskellQuasiQuoted = { link = "onehalfBlueBold" },
        haskellRecursiveDo = { link = "onehalfPurple" },
        haskellQuotedType = { link = "onehalfRed" },
        haskellPreProc = { link = "onehalfFg4" },
        haskellTypeRoles = { link = "onehalfRedBold" },
        haskellTypeForall = { link = "onehalfRed" },
        haskellPatternKeyword = { link = "onehalfBlue" },
        jsonKeyword = { link = "onehalfGreen" },
        jsonQuote = { link = "onehalfGreen" },
        jsonBraces = { link = "onehalfFg1" },
        jsonString = { link = "onehalfFg1" },
        mailQuoted1 = { link = "onehalfAqua" },
        mailQuoted2 = { link = "onehalfPurple" },
        mailQuoted3 = { link = "onehalfYellow" },
        mailQuoted4 = { link = "onehalfGreen" },
        mailQuoted5 = { link = "onehalfRed" },
        mailQuoted6 = { link = "onehalfOrange" },
        mailSignature = { link = "Comment" },
        csBraces = { link = "onehalfFg1" },
        csEndColon = { link = "onehalfFg1" },
        csLogicSymbols = { link = "onehalfFg1" },
        csParens = { link = "onehalfFg3" },
        csOpSymbols = { link = "onehalfFg3" },
        csInterpolationDelimiter = { link = "onehalfFg3" },
        csInterpolationAlignDel = { link = "onehalfAquaBold" },
        csInterpolationFormat = { link = "onehalfAqua" },
        csInterpolationFormatDel = { link = "onehalfAquaBold" },
        rustSigil = { link = "onehalfOrange" },
        rustEscape = { link = "onehalfAqua" },
        rustStringContinuation = { link = "onehalfAqua" },
        rustEnum = { link = "onehalfAqua" },
        rustStructure = { link = "onehalfAqua" },
        rustModPathSep = { link = "onehalfFg2" },
        rustCommentLineDoc = { link = "Comment" },
        rustDefault = { link = "onehalfAqua" },
        ocamlOperator = { link = "onehalfFg1" },
        ocamlKeyChar = { link = "onehalfOrange" },
        ocamlArrow = { link = "onehalfOrange" },
        ocamlInfixOpKeyword = { link = "onehalfRed" },
        ocamlConstructor = { link = "onehalfOrange" },
        LspSagaCodeActionTitle = { link = "Title" },
        LspSagaCodeActionBorder = { link = "onehalfFg1" },
        LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
        LspSagaLspFinderBorder = { link = "onehalfFg1" },
        LspSagaAutoPreview = { link = "onehalfOrange" },
        TargetWord = { fg = colors.blue, bold = config.bold },
        FinderSeparator = { link = "onehalfAqua" },
        LspSagaDefPreviewBorder = { link = "onehalfBlue" },
        LspSagaHoverBorder = { link = "onehalfOrange" },
        LspSagaRenameBorder = { link = "onehalfBlue" },
        LspSagaDiagnosticSource = { link = "onehalfOrange" },
        LspSagaDiagnosticBorder = { link = "onehalfPurple" },
        LspSagaDiagnosticHeader = { link = "onehalfGreen" },
        LspSagaSignatureHelpBorder = { link = "onehalfGreen" },
        SagaShadow = { link = "onehalfBg0" },
        DashboardShortCut = { link = "onehalfOrange" },
        DashboardHeader = { link = "onehalfAqua" },
        DashboardCenter = { link = "onehalfYellow" },
        DashboardFooter = { fg = colors.purple, italic = true },
        MasonHighlight = { link = "onehalfAqua" },
        MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
        MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
        MasonHighlightSecondary = { fg = colors.yellow },
        MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
        MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
        MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
        MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
        MasonMuted = { fg = colors.fg4 },
        MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
        MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
        LspInlayHint = { link = "comment" },
        CarbonFile = { link = "onehalfFg1" },
        CarbonExe = { link = "onehalfYellow" },
        CarbonSymlink = { link = "onehalfAqua" },
        CarbonBrokenSymlink = { link = "onehalfRed" },
        CarbonIndicator = { link = "onehalfGray" },
        CarbonDanger = { link = "onehalfRed" },
        CarbonPending = { link = "onehalfYellow" },
        NoiceCursor = { link = "TermCursor" },
        NoiceCmdlinePopupBorder = { fg = colors.blue, bg = nil },
        NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
        NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
        NoiceCmdlinePopupBorderSearch = { fg = colors.yellow, bg = nil },
        NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },
        NotifyDEBUGBorder = { link = "onehalfBlue" },
        NotifyDEBUGIcon = { link = "onehalfBlue" },
        NotifyDEBUGTitle = { link = "onehalfBlue" },
        NotifyERRORBorder = { link = "onehalfRed" },
        NotifyERRORIcon = { link = "onehalfRed" },
        NotifyERRORTitle = { link = "onehalfRed" },
        NotifyINFOBorder = { link = "onehalfAqua" },
        NotifyINFOIcon = { link = "onehalfAqua" },
        NotifyINFOTitle = { link = "onehalfAqua" },
        NotifyTRACEBorder = { link = "onehalfGreen" },
        NotifyTRACEIcon = { link = "onehalfGreen" },
        NotifyTRACETitle = { link = "onehalfGreen" },
        NotifyWARNBorder = { link = "onehalfYellow" },
        NotifyWARNIcon = { link = "onehalfYellow" },
        NotifyWARNTitle = { link = "onehalfYellow" },
        IlluminatedWordText = { link = "LspReferenceText" },
        IlluminatedWordRead = { link = "LspReferenceRead" },
        IlluminatedWordWrite = { link = "LspReferenceWrite" },
        TSRainbowRed = { fg = colors.red },
        TSRainbowOrange = { fg = colors.orange },
        TSRainbowYellow = { fg = colors.yellow },
        TSRainbowGreen = { fg = colors.green },
        TSRainbowBlue = { fg = colors.blue },
        TSRainbowViolet = { fg = colors.purple },
        TSRainbowCyan = { fg = colors.aqua },
        RainbowDelimiterRed = { fg = colors.red },
        RainbowDelimiterOrange = { fg = colors.orange },
        RainbowDelimiterYellow = { fg = colors.yellow },
        RainbowDelimiterGreen = { fg = colors.green },
        RainbowDelimiterBlue = { fg = colors.blue },
        RainbowDelimiterViolet = { fg = colors.purple },
        RainbowDelimiterCyan = { fg = colors.aqua },
        DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
        DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
        DapUIBreakpointsCurrentLine = { link = "onehalfYellow" },
        DapUIBreakpointsDisabledLine = { link = "onehalfGray" },
        DapUIBreakpointsInfo = { link = "onehalfAqua" },
        DapUIBreakpointsLine = { link = "onehalfYellow" },
        DapUIBreakpointsPath = { link = "onehalfBlue" },
        DapUICurrentFrameName = { link = "onehalfPurple" },
        DapUIDecoration = { link = "onehalfPurple" },
        DapUIEndofBuffer = { link = "EndOfBuffer" },
        DapUIFloatBorder = { link = "onehalfAqua" },
        DapUILineNumber = { link = "onehalfYellow" },
        DapUIModifiedValue = { link = "onehalfRed" },
        DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
        DapUIRestart = { fg = colors.green, bg = colors.bg1 },
        DapUIScope = { link = "onehalfBlue" },
        DapUISource = { link = "onehalfFg1" },
        DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
        DapUIStop = { fg = colors.red, bg = colors.bg1 },
        DapUIStoppedThread = { link = "onehalfBlue" },
        DapUIThread = { link = "onehalfBlue" },
        DapUIType = { link = "onehalfOrange" },
        DapUIUnavailable = { link = "onehalfGray" },
        DapUIWatchesEmpty = { link = "onehalfGray" },
        DapUIWatchesError = { link = "onehalfRed" },
        DapUIWatchesValue = { link = "onehalfYellow" },
        DapUIWinSelect = { link = "onehalfYellow" },
        NeogitDiffDelete = { link = "DiffDelete" },
        NeogitDiffAdd = { link = "DiffAdd" },
        NeogitHunkHeader = { link = "WinBar" },
        NeogitHunkHeaderHighlight = { link = "WinBarNC" },
        DiffviewStatusModified = { link = "onehalfGreenBold" },
        DiffviewFilePanelInsertions = { link = "onehalfGreenBold" },
        DiffviewFilePanelDeletions = { link = "onehalfRedBold" },
        MiniAnimateCursor = { reverse = true, nocombine = true },
        MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
        MiniClueBorder = { link = "FloatBorder" },
        MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
        MiniClueDescSingle = { link = "NormalFloat" },
        MiniClueNextKey = { link = "DiagnosticFloatingHint" },
        MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
        MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
        MiniClueTitle = { link = "FloatTitle" },
        MiniCompletionActiveParameter = { underline = true },
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },
        MiniDepsChangeAdded = { link = "onehalfGreen" },
        MiniDepsChangeRemoved = { link = "onehalfRed" },
        MiniDepsHint = { link = "DiagnosticHint" },
        MiniDepsInfo = { link = "DiagnosticInfo" },
        MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
        MiniDepsPlaceholder = { link = "Comment" },
        MiniDepsTitle = { link = "Title" },
        MiniDepsTitleError = { link = "DiffDelete" },
        MiniDepsTitleSame = { link = "DiffChange" },
        MiniDepsTitleUpdate = { link = "DiffAdd" },
        MiniDiffOverAdd = { link = "DiffAdd" },
        MiniDiffOverChange = { link = "DiffText" },
        MiniDiffOverContext = { link = "DiffChange" },
        MiniDiffOverDelete = { link = "DiffDelete" },
        MiniDiffSignAdd = { link = "onehalfGreen" },
        MiniDiffSignChange = { link = "onehalfAqua" },
        MiniDiffSignDelete = { link = "onehalfRed" },
        MiniFilesBorder = { link = "FloatBorder" },
        MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
        MiniFilesCursorLine = { bg = colors.bg2 },
        MiniFilesDirectory = { link = "Directory" },
        MiniFilesFile = { link = "onehalfFg1" },
        MiniFilesNormal = { link = "NormalFloat" },
        MiniFilesTitle = { link = "FloatTitle" },
        MiniFilesTitleFocused = { link = "onehalfOrangeBold" },
        MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
        MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
        MiniHipatternsTodo = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
        MiniIconsAzure = { link = "onehalfBlue" },
        MiniIconsBlue = { link = "onehalfBlue" },
        MiniIconsCyan = { link = "onehalfAqua" },
        MiniIconsGreen = { link = "onehalfGreen" },
        MiniIconsGrey = { link = "onehalfFg0" },
        MiniIconsOrange = { link = "onehalfOrange" },
        MiniIconsPurple = { link = "onehalfPurple" },
        MiniIconsRed = { link = "onehalfRed" },
        MiniIconsYellow = { link = "onehalfYellow" },
        MiniIndentscopeSymbol = { link = "onehalfGray" },
        MiniIndentscopeSymbolOff = { link = "onehalfYellow" },
        MiniJump = { link = "onehalfOrangeUnderline" },
        MiniJump2dDim = { link = "onehalfGray" },
        MiniJump2dSpot = { fg = colors.orange, bold = config.bold, nocombine = true },
        MiniJump2dSpotAhead = { fg = colors.aqua, bg = colors.bg0, nocombine = true },
        MiniJump2dSpotUnique = { fg = colors.yellow, bold = config.bold, nocombine = true },
        MiniMapNormal = { link = "NormalFloat" },
        MiniMapSymbolCount = { link = "Special" },
        MiniMapSymbolLine = { link = "Title" },
        MiniMapSymbolView = { link = "Delimiter" },
        MiniNotifyBorder = { link = "FloatBorder" },
        MiniNotifyNormal = { link = "NormalFloat" },
        MiniNotifyTitle = { link = "FloatTitle" },
        MiniOperatorsExchangeFrom = { link = "IncSearch" },
        MiniPickBorder = { link = "FloatBorder" },
        MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
        MiniPickBorderText = { link = "FloatTitle" },
        MiniPickIconDirectory = { link = "Directory" },
        MiniPickIconFile = { link = "MiniPickNormal" },
        MiniPickHeader = { link = "DiagnosticFloatingHint" },
        MiniPickMatchCurrent = { bg = colors.bg2 },
        MiniPickMatchMarked = { link = "Visual" },
        MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
        MiniPickNormal = { link = "NormalFloat" },
        MiniPickPreviewLine = { link = "CursorLine" },
        MiniPickPreviewRegion = { link = "IncSearch" },
        MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
        MiniStarterCurrent = { nocombine = true },
        MiniStarterFooter = { link = "onehalfGray" },
        MiniStarterHeader = { link = "Title" },
        MiniStarterInactive = { link = "Comment" },
        MiniStarterItem = { link = "Normal" },
        MiniStarterItemBullet = { link = "Delimiter" },
        MiniStarterItemPrefix = { link = "WarningMsg" },
        MiniStarterSection = { link = "Delimiter" },
        MiniStarterQuery = { link = "MoreMsg" },
        MiniStatuslineDevinfo = { link = "StatusLine" },
        MiniStatuslineFileinfo = { link = "StatusLine" },
        MiniStatuslineFilename = { link = "StatusLineNC" },
        MiniStatuslineInactive = { link = "StatusLineNC" },
        MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, nocombine = true },
        MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.blue, bold = config.bold, nocombine = true },
        MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold, nocombine = true },
        MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.aqua, bold = config.bold, nocombine = true },
        MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red, bold = config.bold, nocombine = true },
        MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green, bold = config.bold, nocombine = true },
        MiniSurround = { link = "IncSearch" },
        MiniTablineCurrent = { fg = colors.green, bg = colors.bg1, bold = config.bold, reverse = config.invert_tabline },
        MiniTablineFill = { link = "TabLineFill" },
        MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        MiniTablineModifiedCurrent = {
            fg = colors.bg1,
            bg = colors.green,
            bold = config.bold,
            reverse = config.invert_tabline,
        },
        MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, reverse = config.invert_tabline },
        MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, reverse = config.invert_tabline },
        MiniTablineTabpagesection = { link = "Search" },
        MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, reverse = config.invert_tabline },
        MiniTestEmphasis = { bold = config.bold },
        MiniTestFail = { link = "onehalfRedBold" },
        MiniTestPass = { link = "onehalfGreenBold" },
        MiniTrailspace = { bg = colors.red },
        WhichKeyTitle = { link = "NormalFloat" },
        NeoTreeFloatBorder = { link = "onehalfGray" },
        NeoTreeTitleBar = { fg = colors.fg1, bg = colors.bg2 },
        NeoTreeDirectoryIcon = { link = "onehalfGreen" },
        NeoTreeDirectoryName = { link = "onehalfGreenBold" },
        ["@comment"] = { link = "Comment" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },
        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.bracket"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Delimiter" },
        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.regexp"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.path"] = { link = "Underlined" },
        ["@string.special.symbol"] = { link = "Identifier" },
        ["@string.special.url"] = { link = "Underlined" },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },
        ["@float"] = { link = "Float" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Special" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },
        ["@constructor"] = { link = "Special" },
        ["@parameter"] = { link = "Identifier" },
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.operator"] = { link = "onehalfRed" },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.storage"] = { link = "StorageClass" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },
        ["@debug"] = { link = "Debug" },
        ["@label"] = { link = "Label" },
        ["@include"] = { link = "Include" },
        ["@exception"] = { link = "Exception" },
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "Type" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@attribute"] = { link = "PreProc" },
        ["@field"] = { link = "Identifier" },
        ["@property"] = { link = "Identifier" },
        ["@variable"] = { link = "onehalfFg1" },
        ["@variable.builtin"] = { link = "Special" },
        ["@variable.member"] = { link = "Identifier" },
        ["@variable.parameter"] = { link = "Identifier" },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Special" },
        ["@constant.macro"] = { link = "Define" },
        ["@markup"] = { link = "onehalfFg1" },
        ["@markup.strong"] = { bold = config.bold },
        ["@markup.italic"] = { link = "@text.emphasis" },
        ["@markup.underline"] = { underline = config.underline },
        ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
        ["@markup.heading"] = { link = "Title" },
        ["@markup.raw"] = { link = "String" },
        ["@markup.math"] = { link = "Special" },
        ["@markup.environment"] = { link = "Macro" },
        ["@markup.environment.name"] = { link = "Type" },
        ["@markup.link"] = { link = "Underlined" },
        ["@markup.link.label"] = { link = "SpecialChar" },
        ["@markup.list"] = { link = "Delimiter" },
        ["@markup.list.checked"] = { link = "onehalfGreen" },
        ["@markup.list.unchecked"] = { link = "onehalfGray" },
        ["@comment.todo"] = { link = "Todo" },
        ["@comment.note"] = { link = "SpecialComment" },
        ["@comment.warning"] = { link = "WarningMsg" },
        ["@comment.error"] = { link = "ErrorMsg" },
        ["@diff.plus"] = { link = "diffAdded" },
        ["@diff.minus"] = { link = "diffRemoved" },
        ["@diff.delta"] = { link = "diffChanged" },
        ["@module"] = { link = "onehalfFg1" },
        ["@namespace"] = { link = "onehalfFg1" },
        ["@symbol"] = { link = "Identifier" },
        ["@text"] = { link = "onehalfFg1" },
        ["@text.strong"] = { bold = config.bold },
        ["@text.emphasis"] = { italic = config.italic.emphasis },
        ["@text.underline"] = { underline = config.underline },
        ["@text.strike"] = { strikethrough = config.strikethrough },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { link = "String" },
        ["@text.uri"] = { link = "Underlined" },
        ["@text.math"] = { link = "Special" },
        ["@text.environment"] = { link = "Macro" },
        ["@text.environment.name"] = { link = "Type" },
        ["@text.reference"] = { link = "Constant" },
        ["@text.todo"] = { link = "Todo" },
        ["@text.todo.checked"] = { link = "onehalfGreen" },
        ["@text.todo.unchecked"] = { link = "onehalfGray" },
        ["@text.note"] = { link = "SpecialComment" },
        ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
        ["@text.warning"] = { link = "WarningMsg" },
        ["@text.danger"] = { link = "ErrorMsg" },
        ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
        ["@text.diff.add"] = { link = "diffAdded" },
        ["@text.diff.delete"] = { link = "diffRemoved" },
        ["@tag"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Identifier" },
        ["@tag.delimiter"] = { link = "Delimiter" },
        ["@punctuation"] = { link = "Delimiter" },
        ["@macro"] = { link = "Macro" },
        ["@structure"] = { link = "Structure" },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@macro" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@constructor" },
        ["@lsp.type.macro"] = { link = "@macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.modifier.java"] = { link = "@keyword.type.java" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.variable"] = { link = "@variable" },

        -- NeoTreeDirectoryName = { link = "Directory" },
        -- NeoTreeDotfile = { fg = colors.fg4 },
        -- NeoTreeFadeText1 = { fg = colors.fg3 },
        -- NeoTreeFadeText2 = { fg = colors.fg4 },
        -- NeoTreeFileIcon = { fg = colors.blue },
        -- NeoTreeFileName = { fg = colors.fg1 },
        -- NeoTreeFileNameOpened = { fg = colors.fg1, bold = true },
        -- NeoTreeFileStats = { fg = colors.fg3 },
        -- NeoTreeFileStatsHeader = { fg = colors.fg2, italic = true },
        -- NeoTreeFilterTerm = { link = "SpecialChar" },
        -- NeoTreeHiddenByName = { link = "NeoTreeDotfile" },
        -- NeoTreeIndentMarker = { fg = colors.fg4 },
        -- NeoTreeMessage = { fg = colors.fg3, italic = true },
        -- NeoTreeModified = { fg = colors.yellow },
        -- NeoTreeRootName = { fg = colors.fg1, bold = true, italic = true },
        -- NeoTreeSymbolicLinkTarget = { link = "NeoTreeFileName" },
        -- NeoTreeExpander = { fg = colors.fg4 },
        -- NeoTreeWindowsHidden = { link = "NeoTreeDotfile" },
        -- NeoTreePreview = { link = "Search" },
        -- NeoTreeGitAdded = { link = "GitGutterAdd" },
        -- NeoTreeGitConflict = { fg = colors.orange, bold = true, italic = true },
        -- NeoTreeGitDeleted = { link = "GitGutterDelete" },
        -- NeoTreeGitIgnored = { link = "NeoTreeDotfile" },
        -- NeoTreeGitModified = { link = "GitGutterChange" },
        -- NeoTreeGitRenamed = { link = "NeoTreeGitModified" },
        -- NeoTreeGitStaged = { link = "NeoTreeGitAdded" },
        -- NeoTreeGitUntracked = { fg = colors.orange, italic = true },
        -- NeoTreeGitUnstaged = { link = "NeoTreeGitConflict" },
        -- NeoTreeTabActive = { fg = colors.fg1, bold = true },
        -- NeoTreeTabInactive = { fg = colors.fg4, bg = colors.bg1 },
        -- NeoTreeTabSeparatorActive = { fg = colors.bg1 },
        -- NeoTreeTabSeparatorInactive = { fg = colors.bg2, bg = colors.bg1 },
    }

    for group, hl in pairs(config.overrides) do
        if groups[group] then
            -- "link" should not mix with other configs (:h hi-link)
            groups[group].link = nil
        end

        groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
    end

    return groups
end

---@param config onehalfConfig?
onehalf.setup = function(config)
    onehalf.config = vim.deepcopy(default_config)
    onehalf.config = vim.tbl_deep_extend("force", onehalf.config, config or {})
end

--- main load function
onehalf.load = function()
    if vim.version().minor < 8 then
        vim.notify_once("onehalf.nvim: you must use neovim 0.8 or higher")
        return
    end

    -- reset colors
    if vim.g.colors_name then
        vim.cmd.hi("clear")
    end
    vim.g.colors_name = "onehalf"
    vim.o.termguicolors = true

    local groups = get_groups()

    -- add highlights
    for group, settings in pairs(groups) do
        vim.api.nvim_set_hl(0, group, settings)
    end
end

return onehalf
